name: travel_seila
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: 
  flutter_riverpod: 
  shared_preferences: 
  go_router: 
  http: 
  url_launcher: 
  random_image_selector:
    path: packages/random_image_selector

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/homescreen_images/
    - assets/fonts/
    
  fonts:
  - family: Montserrat
    fonts:
      - asset: assets/fonts/montserrat/Montserrat-Light.ttf
        weight: 400
      - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        weight: 500
      - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
        weight: 700
      - asset: assets/fonts/montserrat/Montserrat-BoldItalic.ttf
        style: italic
  - family: Ubuntu
    fonts:
      - asset: assets/fonts/ubuntu/Ubuntu-Light.ttf
        weight: 500
      - asset: assets/fonts/ubuntu/Ubuntu-Regular.ttf
        weight: 600
      - asset: assets/fonts/ubuntu/Ubuntu-Bold.ttf
        weight: 700
      - asset: assets/fonts/ubuntu/Ubuntu-BoldItalic.ttf
        style: italic
